question_data = [{"category": "Art", "type": "boolean", "difficulty": "easy",
                   "question": "Leonardo da Vinci's Mona Lisa does not have eyebrows.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Geography", "type": "boolean", "difficulty": "easy",
                   "question": "Alaska is the largest state in the United States.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "General Knowledge", "type": "boolean",
                   "difficulty": "easy",
                   "question": "Nutella is produced by the German company Ferrero.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Science: Gadgets", "type": "boolean",
                   "difficulty": "easy",
                   "question": "The communication protocol NFC stands for Near-Field Control.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                   "question": "According to Greek Mythology, Zeus can control lightning.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "General Knowledge", "type": "boolean",
                   "difficulty": "easy",
                   "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean",
                   "difficulty": "easy",
                   "question": "In the 'Half-Life' series, &quot;H.E.V&quot; stands for 'Hazardous Evasiveness Vest'",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Comics", "type": "boolean",
                   "difficulty": "easy",
                   "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Science & Nature", "type": "boolean",
                   "difficulty": "easy",
                   "question": "An Astronomical Unit is the distance between Earth and the Moon.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Politics", "type": "boolean", "difficulty": "easy",
                   "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
                   "correct_answer": "False", "incorrect_answers": ["True"]}]
